spring.application.name=ai-chat

huggingface.api.key=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
stabilityai.api.key=sk-EZHUl6LLaUIPAvM5CxOoohkqsFJLeszSIdr5Frs3OsZkxm7k
neural4d.api.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgyNTA4LCJpYXQiOjE3Njg5OTY1NzQsImV4cCI6NDkyNDc1NjU3NH0._6ODKbnwBKYABQUheLJ0HNlyHA-yNNZ-CyozsdtAHoA
